# Generated by Django 2.1 on 2018-08-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=20)),
                ('rate', models.CharField(default='', max_length=10)),
                ('release', models.DateField(default='2000-01-01')),
                ('runtime', models.CharField(max_length=10)),
                ('genre', models.TextField(default='')),
                ('director', models.CharField(default='', max_length=200)),
                ('writer', models.TextField(default='')),
                ('plot', models.TextField(default='')),
                ('language', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=100)),
                ('awards', models.TextField(default='')),
                ('poster', models.TextField(default='')),
                ('metascore', models.IntegerField(default=0)),
                ('imdbrating', models.CharField(max_length=10)),
                ('imdbid', models.TextField(default='')),
                ('type', models.TextField(default='')),
                ('dvd', models.DateField(default='2000-01-01')),
                ('boxoffice', models.TextField(default='')),
                ('production', models.TextField(default='')),
                ('website', models.TextField(default='')),
                ('response', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=10)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='movies_app.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_app.Movie'),
        ),
    ]
