# Generated by Django 2.1 on 2018-08-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
    ]
