# Generated by Django 2.1 on 2018-08-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_remove_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='boxoffice',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='dvd',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbid',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdbrating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='metascore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='production',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='movie',
            name='response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='website',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.TextField(default=''),
        ),
    ]
