# Generated by Django 2.1 on 2018-08-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_auto_20180821_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='boxoffice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='dvd',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbid',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='production',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='website',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='writer',
            field=models.TextField(blank=True),
        ),
    ]
